### ISSUE TITLE
Resolve Issues

### ISSUE THREAD

**Issue by PramodGoskula** [Anarghya9751/EMS1-Backend#3]
1. Monolithic Architecture vs. Microservice Architecture:
Consider the benefits of transitioning to a microservice architecture, such as improved scalability, flexibility, and ease of maintenance. Evaluate whether your current monolithic setup meets your current and future needs.

2. Cross-Origin Resource Sharing (CORS):
Implement CORS to allow your frontend application to make requests to your backend API from different origins. This is crucial for web applications that are served from a different domain than the API.

3. DTOs (Data Transfer Objects) and DAOs (Data Access Objects):
Use DTOs to encapsulate data when transferring it between layers of your application (e.g., from controller to service layer or vice versa). DAOs can help in separating the data access logic from your business logic.

4. Method Parameters and Object Usage:
Instead of passing individual parameters, consider using DTOs or a single object to encapsulate related data. This improves readability, maintainability, and reduces the chance of errors.

5. Duplicate Implementations:
Identify and refactor duplicate code and functionalities across your application to adhere to the DRY (Don't Repeat Yourself) principle. This reduces maintenance overhead and potential bugs.

6. Global Exception Handling:
Implement a global exception handling mechanism to centralize error handling and provide consistent responses to clients. This improves the reliability and usability of your APIs.

7. Removing Commented Code:
Clean up commented-out code before pushing changes to your repository. This helps in maintaining a clean codebase and improves readability for other developers.

8. Handling Null Returns:
Instead of returning null when a record is not found, consider throwing an appropriate exception (e.g., NotFoundException). This provides clearer feedback to clients and helps in debugging.

9. App Constants:
Use constants to define values that are used across your application (e.g., error codes, configuration values). This improves maintainability and makes your code more readable.

10. Removing Boilerplate Code:
Identify and refactor boilerplate or duplicate code across your application. This can often be achieved through abstraction, inheritance, or using design patterns where applicable.

11. Email / SMS Notification 
The system does not include functionality for sending email or SMS notifications to users. 

Corrective Actions:
Documentation: Update documentation to reflect changes and improvements made to the codebase.

**Comment by mansoorsonu** [comment]
now the system sends notifications
